name: auto_updater
description: This plugin allows Flutter desktop apps to automatically update themselves (based on sparkle and winsparkle).
version: 0.2.1
homepage: https://github.com/leanflutter/auto_updater

platforms:
  macos:
  windows:

topics:
  - auto-updater

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  auto_updater_macos: ^0.2.0
  auto_updater_platform_interface: ^0.2.0
  auto_updater_windows: ^0.2.1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    platforms:
      macos:
        default_package: auto_updater_macos
      windows:
        default_package: auto_updater_windows
